/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccaRouteImport } from './routes/acca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProRouteImport } from './routes/pro'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ApiPublicCronGradeRouteImport } from './routes/api/public/cron/grade'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccaRoute = AccaRouteImport.update({
  id: '/acca',
  path: '/acca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronGradeRoute = ApiPublicCronGradeRouteImport.update({
  id: '/api/public/cron/grade',
  path: '/api/public/cron/grade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acca': typeof AccaRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/performance': typeof PerformanceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/cron/grade': typeof ApiPublicCronGradeRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acca': typeof AccaRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/performance': typeof PerformanceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/cron/grade': typeof ApiPublicCronGradeRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acca': typeof AccaRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/performance': typeof PerformanceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/cron/grade': typeof ApiPublicCronGradeRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acca'
    | '/auth'
    | '/contact'
    | '/performance'
    | '/privacy-policy'
    | '/pro'
    | '/refund-policy'
    | '/blog/$slug'
    | '/match/$matchId'
    | '/blog/'
    | '/api/public/cron/grade'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acca'
    | '/auth'
    | '/contact'
    | '/performance'
    | '/privacy-policy'
    | '/pro'
    | '/refund-policy'
    | '/blog/$slug'
    | '/match/$matchId'
    | '/blog'
    | '/api/public/cron/grade'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/acca'
    | '/auth'
    | '/contact'
    | '/performance'
    | '/privacy-policy'
    | '/pro'
    | '/refund-policy'
    | '/blog/$slug'
    | '/match/$matchId'
    | '/blog/'
    | '/api/public/cron/grade'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccaRoute: typeof AccaRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PerformanceRoute: typeof PerformanceRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProRoute: typeof ProRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicCronGradeRoute: typeof ApiPublicCronGradeRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acca': {
      id: '/acca'
      path: '/acca'
      fullPath: '/acca'
      preLoaderRoute: typeof AccaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/grade': {
      id: '/api/public/cron/grade'
      path: '/api/public/cron/grade'
      fullPath: '/api/public/cron/grade'
      preLoaderRoute: typeof ApiPublicCronGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccaRoute: AccaRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PerformanceRoute: PerformanceRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProRoute: ProRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  BlogSlugRoute: BlogSlugRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicCronGradeRoute: ApiPublicCronGradeRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
